tap "argon/mas"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "puma/puma"
tap "rcmdnk/file"
tap "sanemat/font"
brew "openssl@1.1"
brew "asciinema"
brew "autoconf"
brew "autoconf@2.13"
brew "automake"
brew "awscli"
brew "fontconfig"
brew "gettext", link: false
brew "libffi"
brew "glib"
brew "cairo"
brew "direnv"
brew "docker"
brew "deepl"
brew "libyaml"
brew "docker-compose", link: false
brew "docker-machine"
brew "fd"
brew "pkg-config"
brew "gobject-introspection"
brew "icu4c"
brew "harfbuzz"
brew "libtool"
brew "pango"
brew "fontforge"
brew "gcc"
brew "gcc@8", link: false
brew "gd"
brew "gh"
brew "gibo"
brew "gist"
brew "git"
brew "python@3.8"
brew "jemalloc"
brew "libtermkey"
brew "libuv"
brew "libvterm"
brew "lua"
brew "luajit"
brew "mackup"
brew "msgpack"
brew "mysql"
brew "neovim"
brew "node"
brew "perl"
brew "postgresql", restart_service: true
brew "python@2", link: false
brew "ruby-build"
brew "rbenv"
brew "rename"
brew "ruby"
brew "spidermonkey"
brew "telnet"
brew "tig"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "argon/mas/mas"
brew "puma/puma/puma-dev"
brew "rcmdnk/file/brew-file"
brew "sanemat/font/ricty"
brew "appcleaner"
cask "blackhole"
cask "adobe-creative-cloud"
cask "dropbox"
cask "rightfont"
cask "toggl-track"
cask "clipy"
cask "clip-studio-paint"
cask "zoom"
cask "visual-studio-code"
cask "figma"
cask "hyperswitch"
cask "google-chrome"
cask "firefox"
cask "discord"
cask "slack"
cask "iterm2"
cask "obs"
mas "Color Ninja", id: 1494948845
mas "Contrast", id: 1254981365
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "macOS Catalinaインストール", id: 0
mas "Microsoft Excel", id: 462058435
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Skitch", id: 425955336
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
