[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'


[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'Shougo/neomru.vim'
hook_add = '''
  nnoremap ,df :<C-u>DeniteBufferDir -buffer-name=files file<CR>
  nnoremap ,db :<C-u>Denite buffer -buffer-name=files file<CR>
  nnoremap ,dr :<C-u>Denite -buffer-name=register register<CR>
  nnoremap ,dm :<C-u>Denite file_mru<CR>
  nnoremap ,g  :<C-u>Denite grep<CR>
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction  
'''
hook_post_source = '''
call denite#custom#option('default', 'prompt', '>')
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set termguicolors
  color iceberg
  syntax on
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline/vim-airline-themes']
hook_add = '''
  source ~/.config/vim/rc/vim-airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1
  let g:auto_save_in_insert_mode = 0
  let g:auto_save_insert_mode = 0
  let g:auto_save_silent = 1
'''

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'othree/es.next.syntax.vim'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tpope/vim-haml'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add='''
let g:vim_markdown_folding_disabled = 1
'''

