# ============================================================================
# Complement
# ============================================================================
[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'statiolake/ddc-ale'
on_source = 'ddc.vim'

[[plugins]]
repo = 'dNitro/vim-pug-complete'
on_ft = ['pug', 'jade']

[[plugins]]
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

# -------------------
# Language Server
# -------------------
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_source = '''
call ddc#custom#patch_global('sources', ['around', 'buffer', 'file', 'nvim-lsp', 'ale'])
call ddc#custom#patch_global('sourceOptions', {
    \ '_': {
    \ 'matchers':   ['matcher_head'],
    \ 'sorters':    ['sorter_rank'],
    \ 'converters': ['converter_remove_overlap'],
    \ },
    \ 'around':   {'mark': 'Around'},
    \ 'buffer':   {'mark': 'Buffer'},
    \ 'file':     {'mark': 'File', 'isVolatile': v:true, 'forceCompletionPattern': '\S/\S*'},
    \ 'nvim-lsp': {'mark': 'LSP', 'forceCompletionPattern': '\.\w*|:\w*|->\w*'}
    \ })
call ddc#custom#patch_global('sourceParams', {
    \ 'around': {'maxSize': 500},
    \ 'buffer': {
    \     'requireSameFiletype': v:false,
    \     'limitBytes': 5000000,
    \     'fromAltBuf': v:true,
    \     'forceCollect': v:true,
    \   },
    \ 'ale': { 'ale': {'cleanResultsWhitespace': v:false} }
    \ })
call ddc#custom#patch_filetype(
    \ ['ps1', 'dosbatch', 'autohotkey', 'registry'], {
    \ 'sourceOptions': {
    \   'file': {
    \     'forceCompletionPattern': '\S\\\S*',
    \   },
    \ },
    \ 'sourceParams': {
    \   'file': {
    \     'mode': 'win32',
    \   },
    \ }})

call ddc#custom#patch_global('ui', 'native')

set completeopt-=preview

inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#map#manual_complete()

inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
on_source = 'ddc.vim'

