# ============================================================================
# User Interface
# ============================================================================
[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
hook_add = '''
nnoremap <silent> ;f <Cmd>Ddu file file_rec -ui-param-startFilter=v:true<CR>
nnoremap <silent> ;b <Cmd>Ddu buffer -ui-param-startFilter=v:false<CR>
nnoremap <silent> ;g <Cmd>Ddu -name=grep rg -ui-param-ignoreEmpty -source-param-input=`input('▶ ')`<CR>
nnoremap <silent> ;n <Cmd>Ddu -name=grep rg -source-param-input=`input('▶ ', expand('<cword>'))`<CR>
'''

hook_source = '''
call ddu#custom#patch_global({
    \  'ui': 'ff',
    \  'sources': [
    \    {'name': 'file'},
    \    {'name': 'file_rec'},
    \    {'name': 'buffer'},
    \    {'name': 'register'},
    \    {'name': 'rg'},
    \  ],
    \  'sourceOptions': {
    \    '_': {
    \      'matchers': ['matcher_substring'],
    \    },
    \    'file_rec': { 'matchers': ['matcher_substring', 'matcher_hidden'] },
    \    'rg': { 'matchers': ['matcher_substring'] },
    \  },
    \   'sourceParams' : {
    \     'rg' : {
    \       'args': ['--column', '--no-heading', '--color', 'never', '--json'],
    \     },
    \   },
    \  'kindOptions': {
    \    'file': {
    \      'defaultAction': 'open',
    \    },
    \  },
    \  'uiParams': {'ff': {
    \    'ignoreEmpty': v:false,
    \    'autoResize': v:false,
    \    'prompt': '▶ ',
    \  }},
    \})

call ddu#custom#patch_local('grep', {
    \   'sourceParams' : {
    \     'rg' : {
    \       'args': ['--column', '--no-heading', '--color', 'never', '--json'],
    \     },
    \   },
    \   'uiParams': {
    \     'ff': {
    \       'ignoreEmpty': v:false,
    \       'autoResize': v:false,
    \       'startFilter': v:false,
    \       'prompt': '▶ ',
    \     }
    \   },
    \ })
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source ='ddu.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
hook_add = '''
autocmd FileType ddu-ff call s:ddu_ff_my_settings()
function! s:ddu_ff_my_settings() abort
  nnoremap <buffer> <CR> <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer> <Space> <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
  nnoremap <buffer> i <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
  nnoremap <buffer> q <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer> <CR> <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
  nnoremap <buffer> <CR> <Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
endfunction
'''

