[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source ='ddu.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
hook_add = '''
autocmd FileType ddu-ff call s:ddu_ff_my_settings()
function! s:ddu_ff_my_settings() abort
  nnoremap <buffer> <CR> <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer> <Space> <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
  nnoremap <buffer> i <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
  nnoremap <buffer> q <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer> <CR> <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
  nnoremap <buffer> <CR> <Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
endfunction
'''

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
hook_add = '''
nnoremap ;g <Cmd>Ddu -name=grep rg -ui-param-ignoreEmpty -source-param-input=`input('Pattern: ')`<CR>
nnoremap ;n <Cmd>Ddu -name=grep rg -source-param-input=`input('Selected: ', expand('<cword>'))`<CR>

call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'sourceOptions': {
    \    'rg': { 'matchers': ['matcher_substring'], 'volatile': v:true, },
    \  },
    \   'sourceParams': {
    \     'rg' : {
    \       'args': ['--column', '--no-heading', '--color', 'never', '--json'],
    \     },
    \   },
    \  'uiParams': {'ff': {
    \    'ignoreEmpty': v:false,
    \  }},
    \ })
'''
