# ============================================================================
# Syntax
# ============================================================================
[[plugins]]
repo = 'othree/html5.vim'
on_ft = [ 'html', 'vue' ]

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass', 'vue']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['jsx']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
hook_post_source = '''
autocmd FileType vue syntax sync fromstart
let g:vue_pre_processors = ['pug', 'scss', 'javascript', 'html']
'''

[[plugins]]
repo = 'lepture/vim-jinja'
on_ft = ['jinja', 'njk']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = [ 'toml' ]

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'scss', 'html', 'vue', 'liquid']
hook_add = '''
let g:user_emmet_settings = {
\  'variables': {'lang': 'ja'},
\  'html': {
\    'default_attributes': {
\      'option': {'value': v:null},
\      'textarea': {'id': v:null, 'name': v:null, 'cols': 10, 'rows': 10},
\    },
\    'snippets': {
\      'html:5': "<!DOCTYPE html>\n"
\              ."<html lang=\"${lang}\">\n"
\              ."<head>\n"
\              ."\t<meta charset=\"${charset}\">\n"
\              ."\t<title></title>\n"
\              ."\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
\              ."</head>\n"
\              ."<body>\n\t${child}|\n</body>\n"
\              ."</html>",
\    },
\  },
\}
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']
hook_post_source = '''
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_conceal = 0
let g:vim_markdown_conceal_code_blocks = 0
'''
