[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
'''

[[plugins]]
repo ='dense-analysis/ale'
on_i = 1
hook_add = '''
let g:ale_linters = {
\   'ruby': ['rubocop'],
\   'javascript': ['eslint'],
\   'typescript': ['eslint', 'tsserver'],
\   'vue': ['eslint'],
\   'css': ['stylelint']
\}
let g:ale_fixers = {
\   'javascript': ['eslint'],
\   'ruby': ['rubocop'],
\   'css': ['stylelint']
\}
let g:ale_javascript_prettier_use_local_config = 1
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

# ============================================================================
# LSP Configuration
# ============================================================================

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = 'ddc.vim'
hook_add = '''
lua << EOF
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true
  require('lspconfig').html.setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
  require('lspconfig').cssls.setup {
    capabilities = capabilities
  }
  require('lspconfig').emmet_ls.setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
  require('lspconfig').solargraph.setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
  require('lspconfig').tsserver.setup {
    on_attach,
    capabilities = capabilities,
    init_options = {
        preferences = {
            disableSuggestions = true,
        },
    },
  }
EOF
'''

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'
hook_add = '''
lua << EOF
  require("mason").setup()
  require("mason-lspconfig").setup {
    ensure_installed = { "cssls", "emmet_ls", "html", "solargraph", "tsserver", "volar" },
  }
EOF
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline/vim-airline-themes']
hook_add = '''
  source ~/.config/nvim/rc/vim-airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1
  let g:auto_save_in_insert_mode = 0
  let g:auto_save_insert_mode = 0
  let g:auto_save_silent = 1
'''

# ============================================================================
# Enhancement
# ============================================================================
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-jp/vital.vim'

# ============================================================================
# grep && replace
# ============================================================================
[[plugins]]
repo = 'thinca/vim-qfreplace'
